/**
 * 
 */
package za.co.juba.system.interfaces.email;

/**
 * @author f3557790 <sabelo.simelane@fnb.co.za>
 */
public enum EmailTemplate {
	FORGOT_PASSWORD, REPORTER_TICKET_COMMENT, REPORTER_TICKET_CREATED, REPORTER_TICKET_REASSIGNED, REPORTER_TICKET_RESOLVED,
	ASSIGNEE_TICKET_ASSIGNED, USER_CREATED, MANAGING_AGENT_TICKET_ASSIGNED, PASSWORD_RESET;
}
